Rdma should contain mapStringObjects instead of additionalProperties.
opencontainers/runtime-spec pull request #1099
Opened 2021-03-30 09:43 UTC by flouthoc

2021-03-30 09:43 UTC, flouthoc commented
@giuseppe could you please take a look.

2021-03-30 09:44 UTC, flouthoc commented
I think we can also change it to mapStringRdma but dont know if it would be standard convention

2021-04-06 06:17 UTC, AkihiroSuda requested changes
I don't think we can have any breaking change in this repo (for v1.x.x, at least)

2021-04-06 06:30 UTC, flouthoc commented
@AkihiroSuda Sure I understand. Probably this pr can never be merged. Just wanted to understand the rationale for choosing map for Rdma devices. I might be missing something but i feel array of struct would be a better choice. As of now strongly-typed parsers will need exception case to handle this as compared to any other type which is added in runtime-spec.

2021-04-09 09:29 UTC, giuseppe commented
@flouthoc are you fine with closing the PR since it would be a breaking change?

2021-04-09 09:37 UTC, closed without merging

2021-04-09 09:38 UTC, flouthoc commented
@giuseppe Sure 😄