add domainname spec entity
opencontainers/runtime-spec pull request #1156
Opened 2022-08-07 18:43 UTC by cdoern

add the domainname entity so that container runtimes can add special handling similar to hostname. The current workaround of adding a sysctl for kernel.domainname only works with rootful execution in most cases. This will allow for rootless execution.

Signed-off-by: Charlie Doern <cdoern@redhat.com>

2022-08-07 18:43 UTC, cdoern commented
@giuseppe PTAL

2022-08-08 06:56 UTC, flouthoc requested changes
I think this should also update the config schema
```diff
diff --git a/schema/config-schema.json b/schema/config-schema.json
index a4d1274..cf66c65 100644
--- a/schema/config-schema.json
+++ b/schema/config-schema.json
@@ -35,6 +35,9 @@
         "hostname": {
             "type": "string"
         },
+        "domainname": {
+            "type": "string"
+        },
         "mounts": {
             "type": "array",
             "items": {
```

2022-08-08 07:09 UTC, flouthoc commented
Nit:
>This will allow for rootless execution

I think in commit message following must be extended to specify how a `container-runtime` should utilize this field, two approach i could  think are runtime invokes `setdomainname(` or the second one is write `/proc/sys/kernel/domainname` before setting up UTS namespace but is it possible in rootless session ? (Requesting maintainers to confirm)

2022-08-08 07:56 UTC, giuseppe commented
as @flouthoc pointed out, please update the config schema as well

2022-08-08 15:19 UTC, giuseppe approved these changes
LGTM

2022-08-10 02:08 UTC, AkihiroSuda approved these changes

2022-08-10 02:46 UTC, AkihiroSuda commented
What should happen if the sysctl is also specified but with a different value? Should it fail?

2022-08-10 03:09 UTC, flouthoc commented
@AkihiroSuda Afaik In crun i think sysctl is not allowed at all if spec already has a knob to configure it for instance i can see for `kernel/hostname` : https://github.com/containers/crun/blob/main/src/libcrun/linux.c#L3198

2022-08-24 02:38 UTC, AkihiroSuda commented
@opencontainers/runtime-spec-maintainers Can we merge this?

2022-08-25 21:28 UTC, vbatts approved these changes

2022-08-25 21:28 UTC, merged