doc:fix poststart doc
opencontainers/runtime-spec pull request #1259
Opened 2024-07-13 13:09 UTC by ningmingxiao

2024-07-13 16:21 UTC, kolyshkin requested changes
This change is obviously wrong, or perhaps I'm missing something here?

Looking into runc sources, I see that poststart is run right after we start init, but before we tell it to continue. This is kind of what the current doc says.

2024-07-13 18:35 UTC, ningmingxiao commented
> This change is obviously wrong, or perhaps I'm missing something here?
> 
> Looking into runc sources, I see that poststart is run right after we start init, but before we tell it to continue. This is kind of what the current doc says.

what doesn;t  "user-specified process" means ?
```
{
    "ociVersion": "1.0.2-dev",
    "process": {
            "terminal": false,
            "user": {
                    "uid": 0,
                    "gid": 0
            },
            "args": [
                    "sh"
            ],
....
```
does it refer to this run custom process ? In runc start

2024-07-14 04:12 UTC, utam0k commented
> what does "user-specified process" means ?

It means a container process. I've double-checked runc's code, and I found a poststart hook is kicked after a container process started.

https://github.com/opencontainers/runc/blob/3778ae603c706494fd1e2c2faf83b406e38d687d/libcontainer/container_linux.go#L350-L352

https://github.com/opencontainers/runc/blob/3778ae603c706494fd1e2c2faf83b406e38d687d/libcontainer/container_linux.go#L362-L367

2024-07-14 04:13 UTC, utam0k commented
Feel free to re-open if there is anything you want to discuss.

2024-07-14 05:22 UTC, ningmingxiao commented
config.json
```
{
    "ociVersion": "1.0.2-dev",
    "process": {
            "terminal": false,
            "user": {
                    "uid": 0,
                    "gid": 0
            },
            "args": [
                    "sh"
            ],
            "env": [
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "TERM=xterm"
            ],
            "cwd": "/",
            "capabilities": {
                    "bounding": [
                            "CAP_AUDIT_WRITE",
                            "CAP_KILL",
                            "CAP_NET_BIND_SERVICE"
                    ],
                    "effective": [
                            "CAP_AUDIT_WRITE",
                            "CAP_KILL",
                            "CAP_NET_BIND_SERVICE"
                    ],
                    "permitted": [
                            "CAP_AUDIT_WRITE",
                            "CAP_KILL",
                            "CAP_NET_BIND_SERVICE"
                    ],
                    "ambient": [
                            "CAP_AUDIT_WRITE",
                            "CAP_KILL",
                            "CAP_NET_BIND_SERVICE"
                    ]
            },
            "rlimits": [
                    {
                            "type": "RLIMIT_NOFILE",
                            "hard": 1024,
                            "soft": 1024
                    }
            ],
            "noNewPrivileges": true
    },
    "root": {
            "path": "rootfs",
            "readonly": false
    },
    "hostname": "runc",
    "mounts": [
            {
                    "destination": "/proc",
                    "type": "proc",
                    "source": "proc"
            },
            {
                    "destination": "/dev",
                    "type": "tmpfs",
                    "source": "tmpfs",
                    "options": [
                            "nosuid",
                            "strictatime",
                            "mode=755",
                            "size=65536k"
                    ]
            },
            {
                    "destination": "/dev/pts",
                    "type": "devpts",
                    "source": "devpts",
                    "options": [
                            "nosuid",
                            "noexec",
                            "newinstance",
                            "ptmxmode=0666",
                            "mode=0620"
                    ]
            },
            {
                    "destination": "/dev/shm",
                    "type": "tmpfs",
                    "source": "shm",
                    "options": [
                            "nosuid",
                            "noexec",
                            "nodev",
                            "mode=1777",
                            "size=65536k"
                    ]
            },
            {
                    "destination": "/dev/mqueue",
                    "type": "mqueue",
                    "source": "mqueue",
                    "options": [
                            "nosuid",
                            "noexec",
                            "nodev"
                    ]
            },
            {
                    "destination": "/sys",
                    "type": "sysfs",
                    "source": "sysfs",
                    "options": [
                            "nosuid",
                            "noexec",
                            "nodev",
                            "ro"
                    ]
            },
            {
                    "destination": "/sys/fs/cgroup",
                    "type": "cgroup",
                    "source": "cgroup",
                    "options": [
                            "nosuid",
                            "noexec",
                            "nodev",
                            "relatime",
                            "ro"
                    ]
            }
    ],
    "hooks": {
            "Poststart": [
                {
                    "path": "/usr/bin/sleep",
                    "args":  ["/usr/bin/sleep","10"]
                }
            ]
    },
    "linux": {
            "resources": {
                    "devices": [
                            {
                                    "allow": false,
                                    "access": "rwm"
                            }
                    ]
            },
            "uidMappings": [
                    {
                            "containerID": 0,
                            "hostID": 1000,
                            "size": 1
                    }
            ],
            "gidMappings": [
                    {
                            "containerID": 0,
                            "hostID": 1000,
                            "size": 1
                    }
            ],
            "namespaces": [
                    {
                            "type": "pid"
                    },
                    {
                            "type": "network"
                    },
                    {
                            "type": "ipc"
                    },
                    {
                            "type": "uts"
                    },
                    {
                            "type": "mount"
                    }
            ],
            "maskedPaths": [
                    "/proc/acpi",
                    "/proc/asound",
                    "/proc/kcore",
                    "/proc/keys",
                    "/proc/latency_stats",
                    "/proc/timer_list",
                    "/proc/timer_stats",
                    "/proc/sched_debug",
                    "/sys/firmware",
                    "/proc/scsi"
            ],
            "readonlyPaths": [
                    "/proc/bus",
                    "/proc/fs",
                    "/proc/irq",
                    "/proc/sys",
                    "/proc/sysrq-trigger"
            ]
    }
}

```

I set 
```
            "Poststart": [
                {
                    "path": "/usr/bin/sleep",
                    "args":  ["/usr/bin/sleep","10"]
                }
```

```
[root@localhost mycontainer]# time runc create test0001

real    0m10.199s
user    0m0.010s
sys     0m0.035s

```

2024-07-15 02:18 UTC, cyphar commented
@utam0k `process.start` doesn't actually start the process, that's actually the implementation of `runc create`. `runc start` calls `container.Exec`. (Yes this is confusing, this happened because when we added `runc create` we changed the semantics of `runc start` and it seems we forgot to rename the internal functions properly.)

I think this is a runc bug.

@kolyshkin 

> Looking into runc sources, I see that poststart is run right after we start init, but before we tell it to continue. This is kind of what the current doc says.

That is what we are doing, but that's not what the spec says should happen AFAICS. The spec says that we should run `poststart` *after* we the user-specified process is started (so during `runc start`, not `runc create` as we are currently doing).

2024-07-15 02:20 UTC, cyphar requested changes
If runc's behaviour doesn't match the spec then we need to fix runc.

2024-07-15 11:23 UTC, utam0k commented
> @utam0k process.start doesn't actually start the process, that's actually the implementation of runc create. runc start calls container.Exec. (Yes this is confusing, this happened because when we added runc create we changed the semantics of runc start and it seems we forgot to rename the internal functions properly.)

@cyphar @ningmingxiao I revised the runc's code and I found my misunderstanding. Thanks for pointing out it to me 🙏 

> If runc's behaviour doesn't match the spec then we need to fix runc.

+1

2024-07-15 11:41 UTC, ningmingxiao commented
> I wonder if we should check other runtimes ...

crun have same problem

2024-07-15 11:48 UTC, utam0k commented
> > I wonder if we should check other runtimes ...
> 
> crun have same problem

Thanks!

cc: @giuseppe

2024-07-15 11:51 UTC, utam0k commented
> > I wonder if we should check other runtimes ...
> 
> crun have same problem

@ningmingxiao 
youki doesn't have the problem, doesn't it?

```bash
$ time sudo ./youki create -b postStart-bug test
sudo ./youki create -b postStart-bug test  0.00s user 0.01s system 17% cpu 0.047 total
```

https://github.com/containers/youki/blob/9ec0cb2a7716615f259cfe9726cd9ca71ba507d6/crates/libcontainer/src/container/container_start.rs#L71-L78

2024-07-15 11:54 UTC, utam0k commented
> > I wonder if we should check other runtimes ...
> 
> crun have same problem

I can't reproduce it with crun.

```
$ time sudo crun create -b postStart-bug test
sudo crun create -b postStart-bug test  0.00s user 0.01s system 23% cpu 0.035 total

$ crun -v
crun version 1.15
commit: e6eacaf4034e84185fd8780ac9262bbf57082278
rundir: /run/user/1000/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```

2024-07-15 11:55 UTC, utam0k commented
> > I wonder if we should check other runtimes ...
> 
> crun have same problem

@ningmingxiao 
I couldn't reproduce it with crun. How did you check it?

```
$ time sudo crun create -b postStart-bug test
sudo crun create -b postStart-bug test  0.00s user 0.01s system 23% cpu 0.035 total

$ crun -v
crun version 1.15
commit: e6eacaf4034e84185fd8780ac9262bbf57082278
rundir: /run/user/1000/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```

2024-07-15 12:05 UTC, ningmingxiao commented
> ```json
> {
>     "ociVersion": "1.0.2-dev",
>     "process": {
>             "terminal": false,
>             "user": {
>                     "uid": 0,
>                     "gid": 0
>             },
>             "args": [
>                     "sh"
>             ],
>             "env": [
>                     "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                     "TERM=xterm"
>             ],
>             "cwd": "/",
>             "capabilities": {
>                     "bounding": [
>                             "CAP_AUDIT_WRITE",
>                             "CAP_KILL",
>                             "CAP_NET_BIND_SERVICE"
>                     ],
>                     "effective": [
>                             "CAP_AUDIT_WRITE",
>                             "CAP_KILL",
>                             "CAP_NET_BIND_SERVICE"
>                     ],
>                     "permitted": [
>                             "CAP_AUDIT_WRITE",
>                             "CAP_KILL",
>                             "CAP_NET_BIND_SERVICE"
>                     ],
>                     "ambient": [
>                             "CAP_AUDIT_WRITE",
>                             "CAP_KILL",
>                             "CAP_NET_BIND_SERVICE"
>                     ]
>             },
>             "rlimits": [
>                     {
>                             "type": "RLIMIT_NOFILE",
>                             "hard": 1024,
>                             "soft": 1024
>                     }
>             ],
>             "noNewPrivileges": true
>     },
>     "root": {
>             "path": "rootfs",
>             "readonly": false
>     },
>     "hostname": "runc",
>     "mounts": [
>             {
>                     "destination": "/proc",
>                     "type": "proc",
>                     "source": "proc"
>             },
>             {
>                     "destination": "/dev",
>                     "type": "tmpfs",
>                     "source": "tmpfs",
>                     "options": [
>                             "nosuid",
>                             "strictatime",
>                             "mode=755",
>                             "size=65536k"
>                     ]
>             },
>             {
>                     "destination": "/dev/pts",
>                     "type": "devpts",
>                     "source": "devpts",
>                     "options": [
>                             "nosuid",
>                             "noexec",
>                             "newinstance",
>                             "ptmxmode=0666",
>                             "mode=0620"
>                     ]
>             },
>             {
>                     "destination": "/dev/shm",
>                     "type": "tmpfs",
>                     "source": "shm",
>                     "options": [
>                             "nosuid",
>                             "noexec",
>                             "nodev",
>                             "mode=1777",
>                             "size=65536k"
>                     ]
>             },
>             {
>                     "destination": "/dev/mqueue",
>                     "type": "mqueue",
>                     "source": "mqueue",
>                     "options": [
>                             "nosuid",
>                             "noexec",
>                             "nodev"
>                     ]
>             },
>             {
>                     "destination": "/sys",
>                     "type": "sysfs",
>                     "source": "sysfs",
>                     "options": [
>                             "nosuid",
>                             "noexec",
>                             "nodev",
>                             "ro"
>                     ]
>             },
>             {
>                     "destination": "/sys/fs/cgroup",
>                     "type": "cgroup",
>                     "source": "cgroup",
>                     "options": [
>                             "nosuid",
>                             "noexec",
>                             "nodev",
>                             "relatime",
>                             "ro"
>                     ]
>             }
>     ],
>     "hooks": {
>             "Poststart": [
>                 {
>                     "path": "/usr/bin/sleep",
>                     "args":  ["/usr/bin/sleep","10"]
>                 }
>             ]
>     },
>     "linux": {
>             "resources": {
>                     "devices": [
>                             {
>                                     "allow": false,
>                                     "access": "rwm"
>                             }
>                     ]
>             },
>             "uidMappings": [
>                     {
>                             "containerID": 0,
>                             "hostID": 1000,
>                             "size": 1
>                     }
>             ],
>             "gidMappings": [
>                     {
>                             "containerID": 0,
>                             "hostID": 1000,
>                             "size": 1
>                     }
>             ],
>             "namespaces": [
>                     {
>                             "type": "pid"
>                     },
>                     {
>                             "type": "network"
>                     },
>                     {
>                             "type": "ipc"
>                     },
>                     {
>                             "type": "uts"
>                     },
>                     {
>                             "type": "mount"
>                     }
>             ],
>             "maskedPaths": [
>                     "/proc/acpi",
>                     "/proc/asound",
>                     "/proc/kcore",
>                     "/proc/keys",
>                     "/proc/latency_stats",
>                     "/proc/timer_list",
>                     "/proc/timer_stats",
>                     "/proc/sched_debug",
>                     "/sys/firmware",
>                     "/proc/scsi"
>             ],
>             "readonlyPaths": [
>                     "/proc/bus",
>                     "/proc/fs",
>                     "/proc/irq",
>                     "/proc/sys",
>                     "/proc/sysrq-trigger"
>             ]
>     }
> }
> ```

I recheck crun it is ok.

2024-07-16 15:21 UTC, lifubang commented
https://github.com/opencontainers/runc/pull/4348#discussion_r1679586846

Could you please help to check this in crun and youki? Thanks.

2024-07-19 11:11 UTC, utam0k commented
> [opencontainers/runc#4348 (comment)](https://github.com/opencontainers/runc/pull/4348#discussion_r1679586846)
> 
> Could you please help to check this in crun and youki? Thanks.

As far as my investigation, the latest crun and youki couldn't reproduce this issue.

2026-03-18 18:06 UTC, giuseppe reviewed
@ningmingxiao still working on this?  Can we close it?

2026-03-19 08:51 UTC, closed without merging