zos updates
opencontainers/runtime-spec pull request #1273
Opened 2024-12-30 16:03 UTC by kershawmehta

This PR proposes updates to the OCI runtime spec with z/OS platform-specific details, including adding **namespaces**, adding **noNewPrivileges** flag, and removing **devices**.  These changes are currently in use by the IBM z/OS Container Platform (zOSCP) product - details can be found here: [https://www.ibm.com/products/zos-container-platform](https://www.ibm.com/products/zos-container-platform).

**Note:** The "removing of devices" is not considered to be an incompatible change since no user would have been using the z/OS-specific portion of the runtime spec, prior to the initial zOSCP release.

2024-12-30 17:42 UTC, thaJeztah commented
Only glancing over; would it be clearer to move the removal of devices to a separate commit? Currently it made me almost consider that "namespaces" was a _replacement_ for devices which was a bit confusing.

2024-12-30 17:59 UTC, AkihiroSuda commented on config-zos.md
> +    * **`mount`** the container will have an isolated mount table.
Is there a public man page like https://man7.org/linux/man-pages/man7/mount_namespaces.7.html ?

2025-01-08 01:54 UTC, AkihiroSuda commented on schema/test/config/good/zos-example.json
> +    "ociVersion": "0.5.0-dev",
nit: invalid version

2025-01-08 01:55 UTC, AkihiroSuda approved these changes

2025-01-08 16:12 UTC, kershawmehta commented on config-zos.md
> +    * **`mount`** the container will have an isolated mount table.
On the z/OS platform, we do not have published static man pages. Rather our man pages are created dynamically (JIT) when the man is issued for a specific command, using a specially formatted version of the documentation. However, we have publicly available documentation and I will push a commit that adds a URL which points to this documentation.

2025-01-08 16:21 UTC, kershawmehta commented on schema/test/config/good/zos-example.json
> +    "ociVersion": "0.5.0-dev",
The ociVersion is the same as used in `spec-example.json`.

2025-01-08 16:25 UTC, kershawmehta commented
> Or is it a replacement? 🙈

The deletion of devices and the addition of namespaces are unrelated. However, I thought that having these in a single PR would be more efficient, given this is the resultant of what is supported by z/OS Container Platform. 
If this really needs to be split into separate PRs, we can do that also.

2025-01-16 01:15 UTC, kolyshkin requested changes
Please amend the first commit to provide a better commit message than "zos updates". You can start by taking the description of this PR and copy-paste it.

2025-01-16 19:35 UTC, kershawmehta commented
> Please amend the first commit to provide a better commit message than "zos updates". You can start by taking the description of this PR and copy-paste it.

Done.

2025-01-30 03:50 UTC, kolyshkin approved these changes
lgtm

2025-01-30 03:50 UTC, merged